jwt:
  secret: pet_project

server:
  port: 8080

spring:
  cache:
    type: redis
  data:
    redis:
      host: redis-service
      port: 6379
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth_service
          uri: http://auth-service:8081
          predicates:
            - Path=/auth/**,/user/**
        - id: question_bank
          uri: http://questbank-service:8082
          predicates:
            - Path=/question/**,/topic/**
