jwt:
  secret: pet_project

server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth_service
          uri: http://auth-service:8081
          predicates:
            - Path=/auth/**,/user/**
        - id: question_bank
          uri: http://questbank-service:8082
          predicates:
            - Path=/question/**